Traceback (most recent call last):
  File "/app/docker/jetson/setup.py", line 3, in <module>
    process = subprocess.Popen(["ros2", "run", "realsense2_camera", "realsense2_camera_node"])
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ros2'
Traceback (most recent call last):
  File "/app/docker/jetson/setup.py", line 3, in <module>
    process = subprocess.Popen(["ros2", "run", "realsense2_camera", "realsense2_camera_node"])
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ros2'
Traceback (most recent call last):
  File "/app/docker/jetson/setup.py", line 3, in <module>
    process = subprocess.Popen(["ros2", "run", "realsense2_camera", "realsense2_camera_node"])
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ros2'
Traceback (most recent call last):
  File "/app/docker/jetson/setup.py", line 3, in <module>
    process = subprocess.Popen(["ros2", "run", "realsense2_camera", "realsense2_camera_node"])
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ros2'
Traceback (most recent call last):
  File "/app/docker/jetson/setup.py", line 3, in <module>
    process = subprocess.Popen(["ros2", "run", "realsense2_camera", "realsense2_camera_node"])
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ros2'
Traceback (most recent call last):
  File "/app/docker/jetson/setup.py", line 3, in <module>
    process = subprocess.Popen(["ros2", "run", "realsense2_camera", "realsense2_camera_node"])
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ros2'
Traceback (most recent call last):
  File "/app/docker/jetson/setup.py", line 3, in <module>
    process = subprocess.Popen(["ros2", "run", "realsense2_camera", "realsense2_camera_node"])
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ros2'
Traceback (most recent call last):
  File "/app/docker/jetson/setup.py", line 3, in <module>
    process = subprocess.Popen(["ros2", "run", "realsense2_camera", "realsense2_camera_node"])
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ros2'
Traceback (most recent call last):
  File "/app/docker/jetson/setup.py", line 3, in <module>
    process = subprocess.Popen(["ros2", "run", "realsense2_camera", "realsense2_camera_node"])
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ros2'
Traceback (most recent call last):
  File "/app/docker/jetson/setup.py", line 3, in <module>
    process = subprocess.Popen(["ros2", "run", "realsense2_camera", "realsense2_camera_node"])
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ros2'
Traceback (most recent call last):
  File "/app/docker/jetson/setup.py", line 3, in <module>
    process = subprocess.Popen(["ros2", "run", "realsense2_camera", "realsense2_camera_node"])
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ros2'
Traceback (most recent call last):
  File "/app/docker/jetson/setup.py", line 3, in <module>
    process = subprocess.Popen(["ros2", "run", "realsense2_camera", "realsense2_camera_node"])
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ros2'
Traceback (most recent call last):
  File "/app/docker/jetson/setup.py", line 3, in <module>
    process = subprocess.Popen(["ros2", "run", "realsense2_camera", "realsense2_camera_node"])
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ros2'
Traceback (most recent call last):
  File "/app/docker/jetson/setup.py", line 3, in <module>
    process = subprocess.Popen(["ros2", "run", "realsense2_camera", "realsense2_camera_node"])
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ros2'
Traceback (most recent call last):
  File "/app/docker/jetson/setup.py", line 3, in <module>
    process = subprocess.Popen(["ros2", "run", "realsense2_camera", "realsense2_camera_node"])
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ros2'
Traceback (most recent call last):
  File "/app/docker/jetson/setup.py", line 3, in <module>
    process = subprocess.Popen(["ros2", "run", "realsense2_camera", "realsense2_camera_node"])
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ros2'
Traceback (most recent call last):
  File "/app/docker/jetson/setup.py", line 3, in <module>
    process = subprocess.Popen(["ros2", "run", "realsense2_camera", "realsense2_camera_node"])
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ros2'
Traceback (most recent call last):
  File "/app/docker/jetson/setup.py", line 3, in <module>
    process = subprocess.Popen(["ros2", "run", "realsense2_camera", "realsense2_camera_node"])
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ros2'
Traceback (most recent call last):
  File "/app/docker/jetson/setup.py", line 3, in <module>
    process = subprocess.Popen(["ros2", "run", "realsense2_camera", "realsense2_camera_node"])
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ros2'
Traceback (most recent call last):
  File "/app/docker/jetson/setup.py", line 3, in <module>
    process = subprocess.Popen(["ros2", "run", "realsense2_camera", "realsense2_camera_node"])
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ros2'
Traceback (most recent call last):
  File "/app/docker/jetson/setup.py", line 3, in <module>
    process = subprocess.Popen(["ros2", "run", "realsense2_camera", "realsense2_camera_node"])
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ros2'
Traceback (most recent call last):
  File "/app/docker/jetson/setup.py", line 3, in <module>
    process = subprocess.Popen(["ros2", "run", "realsense2_camera", "realsense2_camera_node"])
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ros2'
Traceback (most recent call last):
  File "/app/docker/jetson/setup.py", line 3, in <module>
    process = subprocess.Popen(["ros2", "run", "realsense2_camera", "realsense2_camera_node"])
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ros2'
Traceback (most recent call last):
  File "/app/docker/jetson/setup.py", line 3, in <module>
    process = subprocess.Popen(["ros2", "run", "realsense2_camera", "realsense2_camera_node"])
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ros2'
Traceback (most recent call last):
  File "/app/docker/jetson/setup.py", line 3, in <module>
    process = subprocess.Popen(["ros2", "run", "realsense2_camera", "realsense2_camera_node"])
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ros2'
Traceback (most recent call last):
  File "/app/docker/jetson/setup.py", line 3, in <module>
    process = subprocess.Popen(["ros2", "run", "realsense2_camera", "realsense2_camera_node"])
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ros2'
Traceback (most recent call last):
  File "/app/docker/jetson/setup.py", line 3, in <module>
    process = subprocess.Popen(["ros2", "run", "realsense2_camera", "realsense2_camera_node"])
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ros2'
